name: Check

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 20
      - name: Install
        run: yarn
      - name: Lint
        run: yarn test:lint
